### ISSUE TITLE
setup_dev behind main

### ISSUE THREAD

**Issue by SamJCKnox** [CUEDOS/cascade-demo#13]
Is 2 commits behind main. Have approved and pulled the typo fix into main, do you want to delete this branch and start fresh with main?

**Comment by vcrann** [comment]
Let's leave it since Peyman's already started in this branch and we can fix the conflict with the typo when we pull it into main later

**Comment by SamJCKnox** [comment]
is he not in return_dev?

**Comment by vcrann** [comment]
Sorry I just realised you meant setup dev yeah il delete it and start again

**Comment by SamJCKnox** [comment]
I love this issues thing haha
